oauth:
  key-store:
    password: "as1keystore"
    name: "/tmp/askeystore"
  clients:
    client-1-2020: client1
    client-2-2021: client2

server:
  port: 8081

jwt:
  secret: jwttokensecret

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"