oauth:
  key-store:
    password: "client1keystore"
    name: "clientkeystore"
  client: "client-1-2020"
  secret: "client1"
  callback: "http://localhost:8080/callback"
  nodes:
    as_authorization_code: "http://localhost:8081/oauth/authorize"
    #https://github.com/login/oauth/authorize
    as_token: "http://localhost:8081/oauth/token"

api:
  protected:
    employees: "http://localhost:8082/employee/all"

server:
  port: 8080

jwt:
  secret: "jwtclient"