oauth:
  key-store:
    password: "client1keystore"
    name: "clientkeystore"
  client: "client-1-2020"
  secret: "client1"
  callback: "http://localhost:8080/callback"
  nodes:
    authorization-server: "http://localhost:8081/oauth/token"

server:
  port: 8080

jwt:
  secret: "jwtclient"