oauth:
  key-store:
    password: "client1keystore"
    name: "/tmp/clientkeystore"
  client: "client-1-2020"
  secret: "client1"
  callback: "http://oauth.demo.com/code/callback"
  nodes:
    as_authorization_code: "http://oauth.demo.com/oauth/authorize"
    #https://github.com/login/oauth/authorize
    as_token: "http://oauth.demo.com/oauth/token"

api:
  protected:
    employees: "http://localhost:8082/employee/all"

server:
  port: 8080

jwt:
  secret: "jwtclient"

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"